# Generated by Django 3.0.5 on 2020-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200424_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(to='question.Tag'),
        ),
    ]
