# Generated by Django 3.0.5 on 2020-04-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200424_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='question.Tag'),
        ),
    ]
