# Generated by Django 3.0.5 on 2020-04-30 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0004_auto_20200426_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='dislike',
            field=models.ManyToManyField(related_name='q_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='like',
            field=models.ManyToManyField(related_name='q_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
